# ComfyUI — SOTA text-to-image AND text-to-video, plus advanced post-processing
# (SAM segmentation, upscalers) via custom nodes. Runs as a digest-pinned OCI
# container with CDI GPU passthrough (ComfyUI is absent from nixpkgs).
#
# Image: mmartial/comfyui-nvidia-docker — maintained, runs as your UID, persists
# everything (ComfyUI install, custom_nodes, models, output) under a single
# /comfy/mnt mount. We put that mount on /realm so it survives reboots and stays
# off the wear-limited root SSD. Model tree (checkpoints, loras, vae, video
# checkpoints) lives under <mnt>/ComfyUI/models/.
#
# Web UI on 127.0.0.1:8188. text-to-video: install LTX-Video / CogVideoX-2B /
# AnimateDiff / SVD nodes+models from the UI; Wan/Hunyuan GGUF with block-swap
# for the deliberately-slow tier.
{
  mkServiceModule,
  lib,
  pkgs,
  helpers,
  ...
}@args:
mkServiceModule {
  name = "comfyui";
  description = "ComfyUI image/video generation (containerized, CDI GPU)";
  docs = "docs/local-ai-activation.md";
  surface = {
    unit = "podman-comfyui.service";
    resourceClass = "interactive-agent";
    activation = {
      mode = "socket-proxy";
      publicEndpoint = "127.0.0.1:${toString helpers.data.ports.comfyui.public}";
      backendEndpoint = "127.0.0.1:${toString helpers.data.ports.comfyui.backend}";
      idleTimeout = "900s";
      exclusiveResource = "gpu-inference";
      dependsOn = [ "comfyui-proxy" ];
    };
    observe = {
      enable = true;
      restartable = true;
    };
  };
  extraOptions = {
    autoStart = args.lib.mkOption {
      type = args.lib.types.bool;
      default = true;
      description = "Start the ComfyUI container automatically at boot.";
    };
    image = args.lib.mkOption {
      type = args.lib.types.str;
      default = "docker.io/mmartial/comfyui-nvidia-docker@sha256:144dd59ffc29a7c384020eededde1dbfb66d81c6e072c912d51e58becfd3cd00";
      description = "Digest-pinned ComfyUI image. Re-resolve with `skopeo inspect` to update.";
    };
    uid = args.lib.mkOption {
      type = args.lib.types.int;
      default = 1000;
      description = "UID the container drops to (must own the /realm mount).";
    };
    gid = args.lib.mkOption {
      type = args.lib.types.int;
      default = 100; # `users` group
      description = "GID the container drops to.";
    };
  };
  configFn =
    {
      cfg,
      config,
      lib,
      helpers,
      ...
    }:
    let
      user = config.sinnix.user.name;
      mnt = "${config.sinnix.paths.stateRoot}/comfyui";
    in
    {
      sinnix.ml.containerRuntime.enable = true;

      systemd.tmpfiles.rules = [
        "d ${mnt} 0755 ${user} users -"
      ];

      virtualisation.oci-containers.containers.comfyui = {
        inherit (cfg) image;
        inherit (cfg) autoStart;
        # Published on the PRIVATE backend port only -- clients always speak
        # to the public port via comfyui-proxy (modules/services/ai-control.nix),
        # never to the container directly. The container-internal port (right
        # side of the mapping, and COMFYUI_PORT_HOST below) is not a host
        # allocation -- it just happens to numerically match the public port
        # by coincidence, so it stays a literal rather than the registry.
        ports = [ "127.0.0.1:${toString helpers.data.ports.comfyui.backend}:8188" ];
        volumes = [ "${mnt}:/comfy/mnt" ];
        environment = {
          WANTED_UID = toString cfg.uid;
          WANTED_GID = toString cfg.gid;
          SECURITY_LEVEL = "normal";
          COMFYUI_PORT_HOST = "8188";
        };
        # CDI device generated by hardware.nvidia-container-toolkit.
        extraOptions = [ "--device=nvidia.com/gpu=all" ];
      };

      # Bound to the socket proxy's lifecycle: an idle proxy exit tears down
      # this container's cgroup (VRAM release). Conflicts= against every other
      # GPU-inference backend is computed centrally in ai-control.nix's
      # gpuInferenceConflicts.
      systemd.services.podman-comfyui = {
        partOf = [ "comfyui-proxy.service" ];
      };
    };
} args
