# Generated by generate_owner_inputs.py; edit the owner contract.
# Owner source SHA256: ecfd0af79f81c4b6ad465841d51ee2ed19f5a48a97896122cb1cc54297799075
"""Typed inputs for the project owner products, shared by validation and catalog."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class ProjectInput(BaseModel):
    model_config = ConfigDict(extra="forbid")
    project: str = Field(
        min_length=1, max_length=200, pattern=r"^[A-Za-z0-9][A-Za-z0-9_.-]*$"
    )
    roots: list[str] | None = Field(default=None, max_length=100)
    at: str | None = Field(default=None, min_length=1, max_length=512)
    refresh_id: str | None = Field(default=None, min_length=1, max_length=512)


class CampaignInput(ProjectInput):
    roots: list[str] = Field(min_length=1, max_length=100)
    baseline: str | None = Field(default=None, min_length=1, max_length=512)
    relation: Literal["blocks", "parent-child"] = "blocks"
    direction: Literal["prerequisites", "dependents"] = "prerequisites"
    max_nodes: int = Field(default=500, ge=1, le=1000)
    max_depth: int = Field(default=50, ge=1, le=100)


class ScopeInput(CampaignInput):
    baseline: str = Field(min_length=1, max_length=512)


class ContextInput(ProjectInput):
    intent: Literal[
        "project.orientation",
        "project.triage",
        "project.trajectory",
        "verification.regression",
        "incident",
    ] = "project.orientation"
    start: str | None = Field(default=None, pattern=r"^\d{4}-\d{2}-\d{2}$")
    end: str | None = Field(default=None, pattern=r"^\d{4}-\d{2}-\d{2}$")
    budget_bytes: int = Field(
        default=56000,
        ge=8192,
        le=262144,
        description="Presentation target; complete owner component data is retained when exceeded.",
    )


PROJECT_INPUTS: dict[str, type[BaseModel]] = {
    "campaign_evidence": CampaignInput,
    "campaign_progress": CampaignInput,
    "campaign_scope_delta": ScopeInput,
    "verification_regression": ProjectInput,
    "project_trajectory": ProjectInput,
    "project_context": ContextInput,
}


def input_schema(action: str) -> dict[str, Any]:
    schema = PROJECT_INPUTS[action].model_json_schema()
    schema["properties"]["action"] = {
        "type": "string",
        "const": action,
        "default": action,
    }
    return schema
