# Generated by generate_owner_inputs.py; edit the owner contract.
from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal
from pydantic import BaseModel, ConfigDict, Field

class PolylogueStrEnum(StrEnum):
    """Base class for persisted string enums."""

    def __str__(self) -> str:
        return self.value

class Origin(PolylogueStrEnum):
    """Archive source-origin tokens."""

    CLAUDE_CODE_SESSION = "claude-code-session"
    CODEX_SESSION = "codex-session"
    GEMINI_CLI_SESSION = "gemini-cli-session"
    HERMES_SESSION = "hermes-session"
    ANTIGRAVITY_SESSION = "antigravity-session"
    BEADS_ISSUE = "beads-issue"
    GROK_EXPORT = "grok-export"
    CHATGPT_EXPORT = "chatgpt-export"
    CLAUDE_AI_EXPORT = "claude-ai-export"
    # bd polylogue-tbun: Claude Design is a distinct product with its own wire
    # format (camelCase contentBlocks/turnChanges/authorAccountUuid, content
    # is a dict not a list) -- not claude.ai with a flag. See
    # sources/parsers/claude/ai_parser.py's design-chat parser.
    CLAUDE_DESIGN_SESSION = "claude-design-session"
    AISTUDIO_DRIVE = "aistudio-drive"
    UNKNOWN_EXPORT = "unknown-export"

    @classmethod
    def from_string(cls, value: str | Origin | None) -> Origin:
        """Normalize an origin token to the enum, defaulting to UNKNOWN_EXPORT."""
        if value is None:
            return cls.UNKNOWN_EXPORT
        try:
            return cls(str(value))
        except ValueError:
            return cls.UNKNOWN_EXPORT

Bound = Annotated[int, Field(ge=1, le=1000)]

Offset = Annotated[int, Field(ge=0)]

Text = Annotated[str, Field(min_length=1, max_length=8192)]

Continuation = Annotated[str, Field(min_length=1, max_length=65536)]

RawOrigin = Literal["claude-code-session", "codex-session"]

class Request(BaseModel):
    model_config = ConfigDict(extra="forbid")

class SessionList(Request):
    operation: Literal["sessions.list"] = "sessions.list"
    expression: Text | None = None
    origin: Origin | None = None
    tag: str | None = None
    repo: str | None = None
    since: str | None = None
    until: str | None = None
    sort: Literal["date", "tokens", "messages", "words", "longest"] | None = None
    min_messages: Offset | None = None
    max_messages: Offset | None = None
    min_words: Offset | None = None
    limit: Bound = 50
    offset: Offset = 0
    continuation: Continuation | None = None

class SessionSearch(SessionList):
    operation: Literal["sessions.search"] = "sessions.search"

class SessionRead(Request):
    operation: Literal["sessions.read"] = "sessions.read"
    ref: Text
    limit: Bound = 50
    offset: Offset = 0
    continuation: Continuation | None = None

class SessionOrchestration(Request):
    operation: Literal["sessions.orchestration"] = "sessions.orchestration"
    ref: Text

class ResumeContext(Request):
    operation: Literal["context.resume"] = "context.resume"
    session_id: str | None = None
    repo_path: str | None = None
    cwd: str | None = None
    recent_files: list[str] = Field(default_factory=list, max_length=100)
    related_limit: Annotated[int, Field(ge=1, le=20)] = 5

class SessionTimeline(Request):
    operation: Literal["sessions.timeline"] = "sessions.timeline"
    origin: Origin | None = None
    since: str | None = None
    until: str | None = None
    expression: Text | None = None
    limit: Bound = 100
    offset: Offset = 0
    continuation: Continuation | None = None

class RawList(Request):
    operation: Literal["sessions.raw.list"] = "sessions.raw.list"
    origin: RawOrigin
    limit: Bound = 100
    continuation: Text | None = None

class RawSearch(Request):
    operation: Literal["sessions.raw.search"] = "sessions.raw.search"
    origin: RawOrigin
    query: Annotated[str, Field(min_length=1, max_length=1000)]
    reference: Text | None = None
    limit: Bound = 100
    scan_bytes: Annotated[int, Field(ge=1, le=8_388_608)] = 8_388_608
    continuation: Text | None = None

class RawRead(Request):
    operation: Literal["sessions.raw.read", "memory.raw.get"] = "sessions.raw.read"
    reference: Text
    offset: Offset = 0
    max_bytes: Annotated[int, Field(ge=4, le=64_000)] = 64_000

class RawTimeline(Request):
    operation: Literal["sessions.raw.timeline"] = "sessions.raw.timeline"
    origins: list[RawOrigin] = Field(
        default_factory=lambda: list[RawOrigin](["claude-code-session", "codex-session"]), min_length=1, max_length=2
    )
    since: str | None = None
    until: str | None = None
    query: Annotated[str, Field(min_length=1, max_length=1000)] | None = None
    limit: Bound = 100
    scan_bytes: Annotated[int, Field(ge=1, le=8_388_608)] = 8_388_608
    continuation: Text | None = None

class RawMemorySearch(Request):
    operation: Literal["memory.raw.search"] = "memory.raw.search"
    query: Annotated[str, Field(min_length=1, max_length=1000)]
    origins: list[RawOrigin] = Field(
        default_factory=lambda: list[RawOrigin](["claude-code-session", "codex-session"]), min_length=1, max_length=2
    )
    limit: Bound = 100
    scan_bytes: Annotated[int, Field(ge=1, le=8_388_608)] = 8_388_608
    source_cursors: dict[RawOrigin, str | None] | None = None
