"""Stable error codes returned by gateway-owned adapters."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    STALE_CURSOR = "STALE_CURSOR"
    POLICY_DENIED = "POLICY_DENIED"
    OWNER_UNAVAILABLE = "OWNER_UNAVAILABLE"
    AUTHORITY_MISMATCH = "AUTHORITY_MISMATCH"
    RESOURCE_DEFERRED = "RESOURCE_DEFERRED"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
    RESPONSE_BUDGET_EXCEEDED = "RESPONSE_BUDGET_EXCEEDED"
    OPERATION_FAILED = "OPERATION_FAILED"
    RESULT_INVALID = "RESULT_INVALID"
