# Hyprland window rules configuration
{
  windowrule = [
    "idleinhibit focus,class:^(mpv)$"
    "idleinhibit fullscreen,class:^(firefox)$"
    "idleinhibit fullscreen,class:^(google-chrome)$"
    "idleinhibit focus,title:.*[Yy]ou[Tt]ube.*"
    "idleinhibit focus,title:.*- YouTube$"
    "idleinhibit focus,title:.*YouTube.*"
    "idleinhibit focus,title:.*Netflix.*"
    "idleinhibit focus,title:.*Twitch.*"
    "idleinhibit focus,title:.*Prime Video.*"

    "float,title:^(Open File)$"
    "float,title:^(Save As)$"
    "float,class:^(nm-connection-editor)$"
    "float,title:^(Picture-in-Picture)$"
    "pin,title:^(Picture-in-Picture)$"
    "size 480 270,title:^(Picture-in-Picture)$"
    "move 100%-500 50,title:^(Picture-in-Picture)$"
    "workspace special:music,class:^(music)$"
    "workspace special:music,title:^(ncspot)$"
    "workspace special:music,class:^(pwvucontrol)$"
    "workspace special:music,class:^(blueman-manager)$"
    "float,class:^(blueman-manager)$"
    "size 40% 45%,class:^(blueman-manager)$"
    "move 2% 55%,class:^(blueman-manager)$"
    "opacity 0.8 0.8,class:^(pwvucontrol)$"
    "opacity 0.8 0.8,class:^(blueman-manager)$"
    "float,class:^(scratchpad-terminal)$"
    "center,class:^(scratchpad-terminal)$"
    "float,class:^(notes-scratch)$"
    "center,class:^(notes-scratch)$"
    "size 80% 80%,class:^(notes-scratch)$"
    "float,class:(clipse)"
    "center,class:(clipse)"
    "size 2000 1000,class:(clipse)"
    "immediate,class:^(steam_app_.*)$"
    "fullscreen,class:^(steam_app_.*)$"
    "workspace 5,class:^(steam_app_.*)$"
    "float,class:^(xdg-desktop-portal-gtk)$"
    "size 1200 800,class:^(xdg-desktop-portal-gtk)$"
    "float,class:^(imv)$"
    "center,class:^(imv)$"
  ];

  windowrulev2 = [
    "size 60% 100%,title:^(session: )"
    "move 0% 0%,title:^(session: )"
    "tile,class:^(google-chrome)$"
    "float,class:^(google-chrome)$,windowtype:notification,initialTitle:^(?!Untitled - Google Chrome$).*"
    "size 28% 24%,class:^(google-chrome)$,windowtype:notification,initialTitle:^(?!Untitled - Google Chrome$).*"
    "move 70% 6%,class:^(google-chrome)$,windowtype:notification,initialTitle:^(?!Untitled - Google Chrome$).*"
    "float,class:^(google-chrome)$,windowtype:popup,initialTitle:^(?!Untitled - Google Chrome$).*"
    "size 28% 24%,class:^(google-chrome)$,windowtype:popup,initialTitle:^(?!Untitled - Google Chrome$).*"
    "move 70% 6%,class:^(google-chrome)$,windowtype:popup,initialTitle:^(?!Untitled - Google Chrome$).*"
  ];
}
