# Disable default keybindings
input-default-bindings=no

# Default profile
profile=normal

# Start in fullscreen mode
fs=yes

# Display window immediately
force-window=immediate

# Disable hardware decoding
hwdec=no

# Video sync method
video-sync=display-resample

# Subtitle and audio language preferences
slang=en,eng,pl,pol,jp,jpn
alang=jp,jpn,en,eng,pl,pol

# Enable resume playback
resume-playback=yes

# Subtitle appearance
sub-font-size=50
# sub-outline-width=10

######### Profiles ##########

[normal]
ytdl-format=bestvideo[height<=?1440]+bestaudio/best
hr-seek-framedrop=no
scale=ewa_lanczossharp
cscale=spline36
dscale=mitchell
dither-depth=auto
correct-downscaling=yes
sigmoid-upscaling=yes
deband=yes

[wallpaper]
ytdl-format=bestvideo[height<=?1440]+worstaudio/best
loop=
osc=no
no-audio=
input-ipc-server=/tmp/mpvwallpapersocket
scale=spline36
cscale=spline36
dscale=mitchell
dither-depth=no
correct-downscaling=no
sigmoid-upscaling=no
deband=no

[bench]
audio=no
untimed=yes
video-sync=display-desync
opengl-swapinterval=0