# System and Home State Persistence (BTRFS Rollback Impermanence)
#
# ACTIVATION CHECKLIST — all must be true before setting enable = true:
#   [ ] /persist BTRFS subvolume (@persist) exists and is mounted (B2)
#   [ ] SSH host keys and user state migrated to /persist (B5)
#   [ ] @var removed from fileSystems, /var/lib/* migrated to /persist (B6)
#   [ ] @blank read-only snapshot created from clean @ (B7)
#   [ ] initrd rollback script active in storage.nix (B8)
#   [ ] /realm/home bind mount removed from fileSystems (B9)
#
# DO NOT enable until all of the above are confirmed.
#
# ─── IMPERMANENCE MODEL ───────────────────────────────────────────────────────
#
# Root subvolume @ is wiped and restored from @blank on every boot via an
# initrd script in hosts/sinnix-prime/storage.nix. Before wiping, the current
# state is snapshotted to @snapshots/root.boot.TIMESTAMP — so there is always
# a 30d safety window to recover anything forgotten.
#
# The @blank snapshot is a read-only copy of @ taken immediately after a clean
# boot with /persist fully wired and verified. It is the "golden image".
#
# Important state lives on /persist (@persist subvolume, btrbk-snapshotted,
# borg-backed). This module declares which paths are bind-mounted from /persist
# back into the ephemeral @ on every boot.
#
# Future: persistence declarations should eventually be colocated with their
# respective service modules (e.g. sinex module declaring its own /var/lib/sinex
# persistence). This file is the centralised bootstrap until that refactor.
#
# ─── STATE AUDIT (2026-03-08) ─────────────────────────────────────────────────
#
# What currently lives in @ (root subvolume) before impermanence:
#
#   /etc  — 708 KB of real files. Everything else is /nix symlinks, empty
#           mountpoints (/home, /var, /nix, /realm, /outer-realm etc.), or
#           transient runtime dirs (/run, /tmp, /proc, /dev).
#
#   /home — just an empty mountpoint directory (bind-mounted from /realm/home
#           on the SSD_4TB realm device). After B9 it moves INTO @, so /home
#           starts empty each boot and is populated by HM activation + /persist
#           bind-mounts declared below.
#
#   /var  — just an empty mountpoint (@var is a separate BTRFS subvolume).
#           After B6 it moves INTO @, so /var starts empty each boot and is
#           populated by /persist bind-mounts declared below.
#           NOTE: @var is NOT deleted — it remains on disk as a historical
#           archive. Only its fileSystems entry is removed.
#
# ─── /etc REAL FILE ANALYSIS ──────────────────────────────────────────────────
#
# Files in /etc that are NOT regenerated by NixOS activation:
#
#   PERSISTED:
#     /etc/ssh/ssh_host_{rsa,ed25519}_key{,.pub}
#         Unique per-machine SSH host keys. Used by agenix as the root of
#         trust for decrypting all secrets at system activation. If lost:
#         • agenix cannot decrypt any secrets → boot fails
#         • all remote SSH known_hosts entries become invalid
#         • new keys must be generated and all secrets re-encrypted
#
#     /etc/machine-id
#         Affects: dbus session isolation, systemd journal cursor tracking,
#         persistent timer IDs, app fingerprinting (some apps use this as a
#         device identifier). Losing it causes a new ID on next boot, which
#         breaks journal continuity and may confuse some services.
#
#     /etc/adjtime
#         Hardware clock drift calibration written by systemd-timedated.
#         Losing it causes clock skew on next boot until NTP corrects.
#
#   IGNORED (WiFi — desktop is wired-only):
#     /etc/wpa_supplicant/imperative.conf
#         WiFi credentials. Machine is wired-only; WiFi only used during
#         network emergencies. Acceptable to lose.
#
#   IGNORED (generated by NixOS activation):
#     /etc/passwd, /etc/shadow, /etc/group, /etc/sudoers
#     /etc/nix/netrc (generated from secrets)
#     /etc/sinnix/config.json, health-policy.json (runtime sinnix config)
#     /etc/{NIXOS,.clean,.updated}, /etc/kernel/entry-token
#
# ─── /var/lib STATE ANALYSIS ──────────────────────────────────────────────────
#
#   PERSISTED:
#     bluetooth          Paired device keys. Losing = re-pair all BT devices.
#     NetworkManager     Wired profiles, DHCP leases, DNS config.
#     nixos              NixOS activation state (tracks current system closure).
#     systemd            Full systemd state dir:
#                          timers/    — persistent timer last-run timestamps
#                                       (btrbk, borg, and other timers fire
#                                       immediately if this is lost)
#                          random-seed — entropy seed for boot (security)
#                          rfkill/    — radio kill switch state
#                          linger/    — systemd linger list (user services at boot)
#                          timesync/  — time sync state
#                          coredump/  — core dumps (loss is acceptable)
#                          catalog/   — journald catalog (regenerable)
#     sinex              Sinex event platform state database (irreplaceable
#                        telemetry; confirmed in sinex AGENTS.md).
#     transmission       Torrent client state: active torrents, queue, ratios.
#     tailscale          Tailscale auth keys and device identity. Losing =
#                        must re-authenticate to the tailnet and re-issue keys.
#     postgresql         PostgreSQL data directory. Currently mounted, check
#                        active databases with `psql -l` before first boot.
#
#   IGNORED (empty at audit time):
#     sinnix-sentinel    Empty dir — no state yet, add when populated.
#     photoprism         Empty dir — no state yet, add when populated.
#     private            Empty dir — systemd PrivateTmp remnants.
#
#   IGNORED (regenerable / low value):
#     netdata            Metrics history regenerates from live data.
#     onedrive           Can re-authenticate and resync from cloud.
#     onedrive-auth      Same.
#     logrotate.status   Rotation history, harmless to lose.
#     machines           systemd-machined, no containers in use.
#     misc               Systemd misc, regenerable.
#     udisks2            Disk management state, regenerable.
#     upower             Power state, regenerable.
#     lastlog            Login log, low value.
#     portables          systemd portables, not in use.
#
# ─── /home/sinity STATE ANALYSIS ──────────────────────────────────────────────
#
#   PERSISTED (irreplaceable secrets / keys):
#     .ssh
#         SSH identity keys. Second agenix identity path alongside
#         /etc/ssh/ssh_host_ed25519_key. Contains:
#           id_ed25519, id_ed25519.pub         — primary identity
#           id_ed25519_github, *.pub           — GitHub-specific key
#           known_hosts                        — verified host fingerprints
#         Must be migrated to /persist/home/sinity/.ssh/ before B7.
#
#     .gnupg  (mode 0700)
#         GPG keyring. Contains signing key 0x5E6A3B1F used for git commits.
#         Also controls gpg-agent which manages SSH keys via sshcontrol.
#         Losing this means regenerating keys and re-signing infrastructure.
#         Contains: private-keys-v1.d/, pubring.kbx, trustdb.gpg, sshcontrol.
#
#     .config/gh  (mode 0700)
#         GitHub CLI auth. hosts.yml contains OAuth tokens for GitHub API
#         access. Losing = must re-authenticate via `gh auth login`.
#
#     .config/rclone  (mode 0700)
#         rclone remote credentials. rclone.conf contains access keys for
#         cloud storage remotes (Nextcloud, etc.). Losing = re-configure remotes.
#
#   PERSISTED (irreplaceable telemetry / history):
#     .local/share/atuin
#         Shell history database. 97 MB. Years of command history with
#         timestamps, exit codes, working directories. Irreplaceable.
#
#     .local/share/activitywatch
#         ActivityWatch SQLite DB. 674 MB. Continuous window/AFK/browser
#         telemetry. Powers lynchpin analysis. Irreplaceable.
#         Contains: aw-server-rust/sqlite.db, aw-client/queued/
#
#     .config/atuin
#         Atuin config (config.toml). Separate from the DB above.
#         Small but contains sync settings, filter modes, keymap config.
#
#   PERSISTED (large installs, cheaper to persist than rebuild):
#     .local/share/nvim
#         Mason LSP server binaries and treesitter parsers. 1.6 GB.
#         Technically regenerable (mason install + treesitter sync) but
#         takes 30+ minutes and requires network. Cheaper to persist.
#
#     .local/share/Steam  (mode 0750)
#         Steam game library. 65 GB. Root partition is large; keeping games
#         on /persist avoids re-downloading on every boot. If /persist fills
#         up, relocate to /realm/data/libraries/ instead.
#
#   PERSISTED (important UX state):
#     .config/clipse
#         Clipboard history (6 MB). NOTE: config.json and custom_theme.json
#         are HM-managed symlinks to /nix/store — those survive the wipe.
#         Only clipboard_history.json and tmp_files/ (image previews) are
#         real data. Persisting the whole dir is safe.
#
#     .config/qutebrowser  (mode 0700)
#         qutebrowser config, keybinds, quickmarks, user scripts.
#
#     .local/share/qutebrowser  (mode 0700)
#         qutebrowser browsing state: history, sessions, cookies, bookmarks.
#         NOTE: both .config/ and .local/share/ must be persisted —
#         qutebrowser splits its state across both XDG dirs.
#
#     .config/weechat
#         WeeChat config files (servers, nick, plugins). WeeChat splits
#         its state: config in .config/weechat/, runtime state in
#         .local/state/weechat/.
#
#     .local/state/weechat
#         WeeChat runtime state, logs, and buffer state.
#
#     .config/transmission  (mode 0700)
#         Transmission daemon config and per-torrent settings.
#
#     .config/kdeconnect  (mode 0700)
#         KDE Connect device pairing certificates and config.
#         Contains: certificate.pem, privateKey.pem, per-device configs.
#
#     .config/solaar
#         Solaar Logitech peripheral config (device rules, DPI settings).
#
#   PERSISTED (sinex dev / user-space state):
#     .local/state/sinex
#         Sinex user-space state: coordinator, jobs, logs, xtask-history.db.
#         Separate from the system /var/lib/sinex (which is the service DB).
#
#     .local/state/sinex-dev
#         Sinex dev instance state: config, data, run, snapshots, stack.state.
#         Dev environment for sinex development workflow.
#
#     .local/share/nats
#         NATS CLI config and NSC (NATS Security Credentials) state.
#         Contains credentials for NATS cluster access.
#
#   PERSISTED (auth tokens):
#     .claude.json
#         Claude CLI authentication token. Losing = re-authenticate.
#
#   PERSISTED (lazygit state):
#     .local/state/lazygit
#         Lazygit state (recent repos, custom commands history).
#
#   NOT PERSISTED (large, should relocate to /realm instead eventually):
#     .local/share/polylogue      61 GB — already a symlink to /realm/data. ✓
#
#   NOT PERSISTED (regenerable or low-value):
#     .local/share/hyprland       Session compositor state, regenerates.
#     .local/share/zed            Editor extensions/cache, can reinstall.
#     .local/share/gh             GitHub CLI cache (auth is in .config/gh).
#     .local/share/direnv         Compiled env caches, rebuilt by direnv.
#     .local/share/virtualenv     Python venvs, recreated by projects.
#     .local/share/uv             uv package cache, refetched.
#     .local/share/keyrings       GNOME keyring (using gpg-agent for SSH instead).
#
{ lib, config, ... }:
let
  username = config.sinnix.user.name;
in
{
  options.sinnix.persistence.enable = lib.mkEnableOption ''
    BTRFS rollback impermanence — bind-mounts from /persist into ephemeral @.
    See activation checklist at top of this file before enabling.
  '';

  config = lib.mkIf config.sinnix.persistence.enable {

    # ── System persistence ─────────────────────────────────────────────────────
    environment.persistence."/persist" = {
      # Hide bind-mounts from `mount` output to reduce visual noise.
      hideMounts = true;

      directories = [
        "/etc/ssh" # SSH host keys — agenix root of trust (see analysis above)
        "/var/lib/bluetooth" # BT device pairings
        "/var/lib/NetworkManager" # network profiles and DHCP leases
        "/var/lib/nixos" # nixos activation state
        "/var/lib/systemd" # timers, random-seed, rfkill, linger, timesync
        "/var/lib/sinex" # sinex event platform (system service DB)
        "/var/lib/transmission" # torrent daemon state
        "/var/lib/tailscale" # tailscale auth and device identity
        "/var/lib/postgresql" # postgresql data (verify active DBs: `psql -l`)
      ];

      files = [
        "/etc/machine-id" # dbus/journal identity
        "/etc/adjtime" # hardware clock calibration
      ];
    };

    # ── Home persistence ───────────────────────────────────────────────────────
    environment.persistence."/persist".users.${username} = {
      home = "/home/${username}";

      directories = [
        # ── Secrets and keys ──────────────────────────────────────────────────
        {
          directory = ".gnupg"; # GPG keyring + git signing key 0x5E6A3B1F
          mode = "0700";
        }
        ".ssh" # SSH identity keys (second agenix identity path)
        {
          directory = ".config/gh"; # GitHub CLI OAuth tokens
          mode = "0700";
        }
        {
          directory = ".config/rclone"; # rclone remote credentials
          mode = "0700";
        }

        # ── Irreplaceable telemetry ───────────────────────────────────────────
        ".local/share/atuin" # shell history DB, 97 MB
        ".local/share/activitywatch" # AW telemetry DB, 674 MB
        ".config/atuin" # atuin config (separate from DB)

        # ── Large installs (cheaper to persist than rebuild) ──────────────────
        ".local/share/nvim" # Mason LSP servers + treesitter parsers, 1.6 GB
        {
          directory = ".local/share/Steam"; # game library, 65 GB
          mode = "0750";
        }

        # ── Browser state ─────────────────────────────────────────────────────
        {
          directory = ".config/qutebrowser"; # config, keybinds, quickmarks
          mode = "0700";
        }
        {
          directory = ".local/share/qutebrowser"; # history, sessions, cookies
          mode = "0700";
        }

        # ── Clipboard ─────────────────────────────────────────────────────────
        ".config/clipse" # clipboard_history.json + tmp_files/ (config.json is HM symlink)

        # ── IRC ───────────────────────────────────────────────────────────────
        ".config/weechat" # weechat config (servers, nick, plugins)
        ".local/state/weechat" # weechat runtime state and logs

        # ── Torrent ───────────────────────────────────────────────────────────
        {
          directory = ".config/transmission"; # transmission client config
          mode = "0700";
        }

        # ── Peripherals ───────────────────────────────────────────────────────
        {
          directory = ".config/kdeconnect"; # device pairing certs
          mode = "0700";
        }
        ".config/solaar" # Logitech device config

        # ── Sinex dev / user-space state ─────────────────────────────────────
        ".local/state/sinex" # sinex user-space: coordinator, jobs, xtask-history.db
        ".local/state/sinex-dev" # sinex dev instance: config, data, snapshots
        ".local/share/nats" # NATS CLI config and NSC credentials

        # ── Misc tool state ───────────────────────────────────────────────────
        ".local/state/lazygit" # lazygit state (recent repos, history)
      ];

      files = [
        ".claude.json" # Claude CLI auth token
      ];
    };
  };
}
