# System and Home State Persistence (BTRFS Rollback Impermanence)
#
# ACTIVATION CHECKLIST — all confirmed complete as of 2026-03-09:
#   [x] /persist BTRFS subvolume (@persist) exists and is mounted (B2)
#   [x] SSH host keys and user state migrated to /persist (B5)
#   [x] @var removed from fileSystems, /var/lib/* migrated to /persist (B6)
#   [x] @blank read-only snapshot created from clean @ (B7) — done 2026-03-09
#   [x] initrd rollback script active in storage.nix (B8) — activates next boot
#   [x] /realm/home bind mount removed from fileSystems (B9)
#
# STATUS: ACTIVE — 45 bind mounts live, rollback fires from next reboot onward.
#
# ─── IMPERMANENCE MODEL ───────────────────────────────────────────────────────
#
# Root subvolume @ is wiped and restored from @blank on every boot via an
# initrd script in hosts/sinnix-prime/storage.nix. Before wiping, the current
# state is snapshotted to @snapshots/root.boot.TIMESTAMP — so there is always
# a 30d safety window to recover anything forgotten.
#
# The @blank snapshot is a read-only copy of @ taken immediately after a clean
# boot with /persist fully wired and verified. It is the "golden image".
#
# Important state lives on /persist (@persist subvolume, btrbk-snapshotted,
# borg-backed). This module declares which paths are bind-mounted from /persist
# back into the ephemeral @ on every boot.
#
# Future: persistence declarations should eventually be colocated with their
# respective service modules (e.g. sinex module declaring its own /var/lib/sinex
# persistence). This file is the centralised bootstrap until that refactor.
#
# ─── STATE AUDIT (2026-03-09) ─────────────────────────────────────────────────
#
# What currently lives in @ (root subvolume) before impermanence:
#
#   /etc  — 708 KB of real files. Everything else is /nix symlinks, empty
#           mountpoints (/home, /var, /nix, /realm, /outer-realm etc.), or
#           transient runtime dirs (/run, /tmp, /proc, /dev).
#
#   /home — just an empty mountpoint directory (bind-mounted from /realm/home
#           on the SSD_4TB realm device). After B9 it moves INTO @, so /home
#           starts empty each boot and is populated by HM activation + /persist
#           bind-mounts declared below.
#
#   /var  — just an empty mountpoint (@var is a separate BTRFS subvolume).
#           After B6 it moves INTO @, so /var starts empty each boot and is
#           populated by /persist bind-mounts declared below.
#           NOTE: @var is NOT deleted — it remains on disk as a historical
#           archive. Only its fileSystems entry is removed.
#
# ─── /etc REAL FILE ANALYSIS ──────────────────────────────────────────────────
#
#   PERSISTED:
#     /etc/ssh/ssh_host_{rsa,ed25519}_key{,.pub}
#         Unique per-machine SSH host keys. Used by agenix as the root of
#         trust for decrypting all secrets at system activation. If lost:
#         • agenix cannot decrypt any secrets → boot fails
#         • all remote SSH known_hosts entries become invalid
#         • new keys must be generated and all secrets re-encrypted
#
#     /etc/machine-id
#         Affects: dbus session isolation, systemd journal cursor tracking,
#         persistent timer IDs, app fingerprinting. Losing it causes a new ID
#         on next boot, breaking journal continuity.
#
#     /etc/adjtime
#         Hardware clock drift calibration written by systemd-timedated.
#         Losing it causes clock skew on next boot until NTP corrects.
#
#   IGNORED (WiFi — desktop is wired-only):
#     /etc/wpa_supplicant/imperative.conf — WiFi passwords. Acceptable to lose.
#
#   IGNORED (generated by NixOS activation):
#     /etc/passwd, /etc/shadow, /etc/group, /etc/sudoers
#     /etc/nix/netrc, /etc/sinnix/config.json, /etc/sinnix/health-policy.json
#     /etc/{NIXOS,.clean,.updated}, /etc/kernel/entry-token
#
# ─── /var/lib STATE ANALYSIS ──────────────────────────────────────────────────
#
#   PERSISTED:
#     bluetooth          Paired device keys. Losing = re-pair all BT devices.
#     NetworkManager     Wired profiles, DHCP leases, DNS config.
#     nixos              NixOS activation state (tracks current system closure).
#     systemd            Full systemd state dir:
#                          timers/     — persistent timer timestamps (btrbk, borg)
#                          random-seed — entropy seed for boot
#                          rfkill/     — radio kill switch state
#                          linger/     — systemd linger list
#                          timesync/   — time sync state
#                          coredump/   — core dumps (loss acceptable)
#     sinex              Sinex event platform state (system service).
#                        See modules/services/sinex.nix for configuration.
#     transmission       Torrent state: active torrents, queue, ratios.
#     tailscale          Auth keys and device identity. Losing = re-auth.
#     postgresql         Database files. Verify active DBs: `psql -l`.
#
#   IGNORED (empty at audit time — add when populated):
#     sinnix-sentinel, photoprism, private
#
#   IGNORED (regenerable):
#     netdata, onedrive, onedrive-auth, logrotate.status, machines, misc,
#     udisks2, upower, lastlog, portables
#
# ─── /home/sinity STATE ANALYSIS ──────────────────────────────────────────────
#
# NOTE: entries marked "(HM)" are managed by Home Manager and recreated as
# nix store symlinks on every activation — they do NOT need to be persisted.
# Only runtime-written state (auth tokens, databases, history) belongs here.
#
#   PERSISTED (secrets and keys):
#     .gnupg              GPG keyring + signing key 0x5E6A3B1F. Controls git
#                         signing and gpg-agent SSH key management.
#     .ssh                SSH identity keys (second agenix identity path).
#     .config/gh          GitHub CLI OAuth tokens (hosts.yml).
#     .config/rclone      rclone remote credentials (rclone.conf).
#     .config/gcloud      GCloud auth: credentials.db, access_tokens.db,
#                         application_default_credentials.json.
#     .config/cachix      cachix.dhall auth token.
#     .config/io.datasette.llm
#                         LLM CLI state: keys.json (API keys), embeddings.db,
#                         logs.db.
#
#   PERSISTED (auth tokens in config dirs):
#     .config/google-chrome  1.6 GB. Chrome profile: history, extensions,
#                         cookies, passwords, session. Primary browser.
#     .config/spotify     Spotify Desktop auth token.
#     .config/ncspot      ncspot auth (userstate.cbor) + config.
#     .config/imgur-screenshot  settings.conf with upload auth.
#
#   PERSISTED (irreplaceable telemetry):
#     .local/share/atuin  Shell history DB, 97 MB. Irreplaceable.
#     .local/share/activitywatch  AW SQLite DB, 674 MB. Irreplaceable.
#     .config/activitywatch  AW watcher configs (aw-server-rust, aw-client,
#                         aw-watcher-afk, aw-watcher-window-wayland, awatcher).
#                         These are runtime-written, not HM managed.
#     .config/awatcher    awatcher config.toml. Runtime-written.
#
#   PERSISTED (task and time tracking):
#     .config/task        Taskwarrior config.
#     .task               Taskwarrior database (TW3/taskchampion, ~/.task/).
#     .config/timewarrior Timewarrior config.
#     .local/share/timewarrior  Timewarrior time logs.
#
#   PERSISTED (large installs — cheaper to persist than rebuild):
#     .local/share/nvim   Mason LSP servers + treesitter parsers, 1.6 GB.
#     .local/share/Steam  Game library, 65 GB. If /persist fills, relocate
#                         to /realm/data/libraries/.
#
#   PERSISTED (browser state):
#     .config/qutebrowser  qutebrowser config, keybinds, quickmarks.
#     .local/share/qutebrowser  History, sessions, cookies, bookmarks.
#                         NOTE: qutebrowser splits state across both XDG dirs.
#
#   PERSISTED (important UX state):
#     .config/clipse      Clipboard history (6 MB). config.json and
#                         custom_theme.json are HM symlinks; only
#                         clipboard_history.json and tmp_files/ are real data.
#     .config/yazi        Yazi file manager config (keymaps, theme, openers).
#                         Real files with auto-backups — NOT HM managed.
#     .local/share/zoxide Zoxide jump database.
#     .local/share/direnv direnv allowlist (security grants) and env cache.
#                         Losing allowlist = `direnv allow` in every project dir
#                         on first cd. Performance impact: ~1-3s re-eval per
#                         project (nix derivations stay in store, only the
#                         direnv layer re-caches).
#
#   PERSISTED (IRC):
#     .config/weechat     WeeChat config (servers, nick, plugins).
#     .local/state/weechat  WeeChat runtime state and logs.
#
#   PERSISTED (peripherals):
#     .config/kdeconnect  Device pairing certs (certificate.pem, privateKey.pem).
#     .config/solaar      Logitech device config (DPI, rules).
#
#   PERSISTED (torrent):
#     .config/transmission  Transmission client config.
#
#   PERSISTED (AI tools):
#     .claude             Claude Code CLI — single dir for config + state.
#                         HM symlinks (settings.json, CLAUDE.md, skills, world-model,
#                         hooks/) sit alongside runtime state (projects/, history.jsonl,
#                         plugins/, session-env/) — all in one canonical location.
#     .claude.json        Claude CLI auth token (home-root file).
#     .codex              Codex CLI — single dir for config + state (parallel to .claude).
#                         HM symlinks (config.toml, skills/) sit alongside runtime state
#                         (auth.json, history.jsonl, state_5.sqlite, shell_snapshots/).
#
#   NOT PERSISTED — sinex dev state:
#     Current xtask writes to /realm/project/sinex/.sinex/state/ — on /realm,
#     already persisted. No home dir persistence needed.
#     ~/.local/state/sinex/ was from an older xtask binary that used dirs::state_dir()
#     (XDG). Current binary has no such path and the devshell shellHook explicitly
#     sets SINEX_STATE_DIR=$PWD/.sinex/state/ as override. The home path wipes on
#     reboot and will not re-accumulate.
#     See modules/services/sinex.nix for persistence of the system service.
#     TODO: decide and act — add SINEX_STATE_DIR env var or accept loss.
#
#   PERSISTED (polylogue):
#     .config/polylogue    OAuth credentials (polylogue-credentials.json, settings.json).
#     .local/state/polylogue  index.sqlite, token.json, drive_token.json, state.json, runs.json.
#                          Previously lived in /realm/home — migrated to /persist 2026-03-10.
#
#   NOT PERSISTED (large, should relocate to /realm eventually):
#     .local/share/polylogue — already a symlink to /realm/data. ✓
#
#   NOT PERSISTED (HM-managed, recreated on activation):
#     .config/atuin (programs.atuin), .config/bat (programs.bat),
#     .config/broot (programs.broot), .config/btop (programs.btop),
#     .config/mpv (programs.mpv), .config/nvim, .config/kitty, .config/claude,
#     .config/starship.toml, .config/tmux, .config/waybar, .config/hypr,
#     .config/zsh, .config/ripgrep-all, .config/marimo, all stylix targets
#
#   NOT PERSISTED (regenerable):
#     .local/share/hyprland, .local/share/zed, .local/share/gh (cache),
#     .local/share/direnv/allow (covered above), .local/share/virtualenv,
#     .local/share/uv, .local/share/keyrings (using gpg-agent),
#     .local/state/tofi-drun-history, .local/state/wireplumber,
#     .local/state/yazi, .local/state/home-manager
#
{ lib, config, ... }:
let
  username = config.sinnix.user.name;
in
{
  options.sinnix.persistence.enable = lib.mkEnableOption ''
    BTRFS rollback impermanence — bind-mounts from /persist into ephemeral @.
    See activation checklist at top of this file before enabling.
  '';

  config = lib.mkIf config.sinnix.persistence.enable {

    # ── System persistence ─────────────────────────────────────────────────────
    environment.persistence."/persist" = {
      hideMounts = true;

      directories = [
        "/etc/ssh" # SSH host keys — agenix root of trust
        "/var/lib/bluetooth" # BT device pairings
        "/var/lib/NetworkManager" # network profiles
        "/var/lib/nixos" # nixos activation state
        "/var/lib/systemd" # timers, random-seed, rfkill, linger, timesync
        "/var/lib/sinex" # sinex event platform (see services/sinex.nix)
        "/var/lib/transmission" # torrent state
        "/var/lib/tailscale" # tailscale auth and device identity
        "/var/lib/postgresql" # postgresql data (verify: `psql -l`)
        "/var/log/below" # below time-travel resource monitor data
      ];

      files = [
        "/etc/machine-id"
        "/etc/adjtime"
      ];
    };

    # ── Home persistence ───────────────────────────────────────────────────────
    environment.persistence."/persist".users.${username} = {

      directories = [
        # ── Secrets and credentials ───────────────────────────────────────────
        { directory = ".gnupg"; mode = "0700"; } # GPG keyring + git signing key
        ".ssh" # SSH identity keys (second agenix identity path)
        { directory = ".config/gh"; mode = "0700"; } # GitHub CLI OAuth tokens
        { directory = ".config/rclone"; mode = "0700"; } # rclone remote credentials
        { directory = ".config/gcloud"; mode = "0700"; } # GCloud auth + credentials
        ".config/cachix" # cachix auth token
        { directory = ".config/io.datasette.llm"; mode = "0700"; } # LLM CLI API keys + logs

        # ── Browser auth and profile ──────────────────────────────────────────
        { directory = ".config/google-chrome"; mode = "0700"; } # 1.6 GB — primary browser
        { directory = ".config/spotify"; mode = "0700"; } # Spotify Desktop auth
        { directory = ".config/ncspot"; mode = "0700"; } # ncspot auth + config
        ".config/imgur-screenshot" # imgur upload auth

        # ── Irreplaceable telemetry ───────────────────────────────────────────
        ".local/share/atuin" # shell history DB, 97 MB
        ".local/share/activitywatch" # AW SQLite DB, 674 MB
        ".config/activitywatch" # AW watcher configs (runtime-written, not HM)
        ".config/awatcher" # awatcher config.toml

        # ── Task and time tracking ────────────────────────────────────────────
        ".config/task" # taskwarrior config
        ".task" # taskwarrior database (TW3/taskchampion backend uses ~/.task/)
        # NOTE: .local/share/task was the TW2 location — now empty (just hooks/).
        # Removed from persist; TW3 writes to ~/.task/ exclusively.
        ".config/timewarrior" # timewarrior config
        ".local/share/timewarrior" # timewarrior time logs

        # ── Large installs ────────────────────────────────────────────────────
        ".local/share/nvim" # Mason LSP servers + treesitter parsers, 1.6 GB
        { directory = ".local/share/Steam"; mode = "0750"; } # game library, 65 GB

        # ── Browser state ─────────────────────────────────────────────────────
        { directory = ".config/qutebrowser"; mode = "0700"; }
        { directory = ".local/share/qutebrowser"; mode = "0700"; } # history, sessions, cookies

        # ── UX state ─────────────────────────────────────────────────────────
        ".config/clipse" # clipboard history (config.json is HM symlink, data is real)
        ".config/yazi" # yazi config: keymaps, theme, openers (real files, not HM)
        ".local/share/zoxide" # jump database
        ".local/share/direnv" # allowlist (security grants) + env cache

        # ── IRC ───────────────────────────────────────────────────────────────
        ".config/weechat"
        ".local/state/weechat"

        # ── Peripherals ───────────────────────────────────────────────────────
        { directory = ".config/kdeconnect"; mode = "0700"; } # device pairing certs
        ".config/solaar" # Logitech device config

        # ── Torrent ───────────────────────────────────────────────────────────
        { directory = ".config/transmission"; mode = "0700"; }

        # ── Polylogue ─────────────────────────────────────────────────────────
        { directory = ".config/polylogue"; mode = "0700"; } # OAuth credentials
        { directory = ".local/state/polylogue"; mode = "0700"; } # index.sqlite, tokens, state

        # ── AI tools ──────────────────────────────────────────────────────────
        # ~/.claude: single source of truth for all Claude Code state.
        # HM manages config symlinks (settings.json, CLAUDE.md, skills, etc.) directly
        # inside this dir. Runtime state (projects/, history.jsonl, etc.) coexists.
        # ~/.config/claude is ephemeral — not persisted (HM-managed files are recreated).
        { directory = ".claude"; mode = "0700"; }
        # ~/.codex: Codex CLI — same pattern as .claude.
        # HM manages config symlinks (config.toml, skills/) inside this dir.
        # Runtime state (auth.json, history.jsonl, state_5.sqlite, shell_snapshots/) coexists.
        { directory = ".codex"; mode = "0700"; }
      ];

      files = [
        ".claude.json" # Claude CLI auth token (home-root)
      ];
    };
  };
}
