{ pkgs, inputs, ... }:
let
  polyloguePackage = inputs.polylogue.packages.${pkgs.stdenv.system}.polylogue;
  sinevecPackage = inputs.sinevec.packages.${pkgs.stdenv.system}.sinevec;
in
{
  environment.systemPackages =
    (with pkgs; [
    git
    git-annex
    gnumake
    gcc
    gdb
    scc
    gource
    cargo-audit
    cargo-outdated
    cargo-deny
    cargo-bloat
    cargo-expand
    cargo-flamegraph
    cargo-llvm-lines
    cargo-udeps
    cargo-depgraph
    cargo-machete
    tokei
    onefetch
    git-cliff
    cocogitto
    hyperfine
    gitui
    lazygit
    gitstats
    graphviz
    plantuml
    d2
    mermaid-cli
    pikchr
    structurizr-cli
    gnuplot
    ploticus
    sqlite
    duckdb
    jq
    miller
    xan
    visidata
    nix-diff
    nix-tree
    nix-prefetch-git
    nix-health
    nix-zsh-completions
    nix-fast-build
    nix-doc
    nix-index
    cmake
    meson
    ninja
    uv
    man-pages
    man-pages-posix
    claude-code-usage-monitor
    dtach
    mprocs
    btop
    ncdu
    nitch
    dua
    yazi
    fselect
    zk
    toipe
    ttyper
    cbonsai
    pipes
    tty-clock
    mesa-demos
    vulkan-tools
    vulkan-validation-layers
    wayland-utils
    libva-utils
    glxinfo
    drm_info
    inxi
    hwinfo
    dmidecode
    lm_sensors
    nvme-cli
    smartmontools
    powertop
    stressapptest
    stress-ng
    sysbench
    phoronix-test-suite
    glmark2
    vkmark
    fio
    perf
    sysstat
    memtester
    rt-tests
    linuxPackages.turbostat
    hdparm
    ethtool
    iperf3
    netperf
    s-tui
    intel-gpu-tools
    python312Packages.speedtest-cli
    breakpad
    flent
    gum
    google-cloud-sdk
    linuxPackages.cpupower
  ])
    ++ [ polyloguePackage sinevecPackage ];

  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      stdenv.cc.cc
      openssl
      curl
      glib
      util-linux
      glibc
      icu
      libunwind
      libuuid
      zlib
      libsecret
      freetype
      libglvnd
      libnotify
      SDL2
      vulkan-loader
      gdk-pixbuf
      pipewire
      pulseaudio
      alsa-lib
      at-spi2-atk
      at-spi2-core
      atk
      cairo
      cups
      dbus
      expat
      fontconfig
      fuse3
      gtk3
      libGL
      libappindicator-gtk3
      libdrm
      libpulseaudio
      libuuid
      nspr
      nss
      pango
      systemd
      xorg.libX11
      xorg.libXScrnSaver
      xorg.libXcomposite
      xorg.libXcursor
      xorg.libXdamage
      xorg.libXext
      xorg.libXfixes
      xorg.libXi
      xorg.libXrandr
      xorg.libXrender
      xorg.libXtst
      xorg.libxcb
      xorg.libxkbfile
      xorg.libxshmfence
    ];
  };
}
