#!/usr/bin/env bash

xset dpms force on
pulseaudio-control --volume-max 100 --volume-step 100 down
pulseaudio-control --volume-max 100 --volume-step 18 up
sleep 1
yeelight_toggle 0
sleep 10
pulseaudio-control --volume-max 100 --volume-step 10 up
sleep 10
#playerctl play

for i in `seq 1 55`;
do
  pulseaudio-control --volume-max 100 --volume-step 1 up
  sleep 1
done
