-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
--
-- VS Code-embedded sessions get their maps from lua/vscode_keymaps.lua;
-- standalone-only maps live in the plugin specs (lua/plugins/*.lua) so
-- which-key can attribute and lazy-load them.
