"""Copy standalone Pydantic owner contracts without reinterpreting their schemas.

Usage: python generate_owner_inputs.py --lynchpin /path/to/owner/lynchpin/mcp/project_contracts.py
The emitted model module is checked in; regenerate when the pinned owner changes.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
from pathlib import Path


def generated(source: Path) -> str:
    content = source.read_bytes()
    return (
        "# Generated by generate_owner_inputs.py; edit the owner contract.\n"
        f"# Owner source SHA256: {hashlib.sha256(content).hexdigest()}\n"
        + content.decode()
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lynchpin", type=Path)
    parser.add_argument("--polylogue", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {}
    if args.lynchpin:
        outputs["generated_lynchpin_inputs.py"] = generated(args.lynchpin)
    if args.polylogue:
        source = args.polylogue / "polylogue/operations/session_contracts.py"
        content = source.read_text()
        tree = ast.parse(content)
        names = {
            "Bound",
            "Offset",
            "Text",
            "Continuation",
            "RawOrigin",
            "Request",
            "SessionList",
            "SessionSearch",
            "SessionRead",
            "SessionOrchestration",
            "ResumeContext",
            "SessionTimeline",
            "RawList",
            "RawSearch",
            "RawRead",
            "RawTimeline",
            "RawMemorySearch",
        }
        selected = []
        for node in tree.body:
            name = (
                node.name
                if isinstance(node, ast.ClassDef)
                else (
                    node.targets[0].id
                    if isinstance(node, ast.Assign)
                    and isinstance(node.targets[0], ast.Name)
                    else None
                )
            )
            if name in names:
                selected.append(ast.get_source_segment(content, node))
        enums = (args.polylogue / "polylogue/core/enums.py").read_text()
        classes = {
            node.name: ast.get_source_segment(enums, node)
            for node in ast.parse(enums).body
            if isinstance(node, ast.ClassDef)
        }
        identities = classes["PolylogueStrEnum"] + "\n\n" + classes["Origin"]
        content = (
            "# Generated by generate_owner_inputs.py; edit the owner contract.\n"
            "from __future__ import annotations\n\nfrom enum import StrEnum\n"
            "from typing import Annotated, Literal\n"
            "from pydantic import BaseModel, ConfigDict, Field\n\n"
            + identities
            + "\n\n"
            + "\n\n".join(selected)
        )
        outputs["generated_polylogue_inputs.py"] = content + "\n"
    if not outputs:
        parser.error("supply at least one owner source")
    for filename, content in outputs.items():
        destination = Path(__file__).parent / "sinnix_agent_gateway" / filename
        if args.check:
            if destination.read_text() != content:
                raise SystemExit(f"generated owner input models are stale: {filename}")
        else:
            destination.write_text(content)


if __name__ == "__main__":
    main()
