# OpenWrt UCI generation library
#
# Translates declarative Nix attrsets into deterministic UCI shell commands.
# Designed to be consumed by the router flake module to produce a deployable
# configure.sh script.
#
# Conventions:
#   - uciPackage: the UCI config package name (network, wireless, dhcp, …)
#   - sections: attrset of { sectionName = { _type = "…"; option = value; list = [v…]; }; }
#   - Lists become repeated `uci add_list` calls
#   - Booleans become "1"/"0" strings
#   - The special key `_type` sets the section type; `_anonymous` creates unnamed sections
{ lib }:

let
  # Escape a single-quoted UCI value
  escapeVal = v: builtins.replaceStrings [ "'" ] [ "'\"'\"'" ] (toString v);

  # Render a single scalar value
  renderValue = v: if lib.isBool v then (if v then "1" else "0") else toString v;

  # Emit UCI commands for one option key/value within a section path
  renderOption =
    path: key: val:
    if lib.isList val then
      # Delete existing list entries first, then re-add each
      "uci delete '${escapeVal path}.${key}' 2>/dev/null || true\n"
      + lib.concatMapStringsSep "\n" (
        v: "uci add_list '${escapeVal path}.${key}=${escapeVal (renderValue v)}'"
      ) val
    else
      "uci set '${escapeVal path}.${key}=${escapeVal (renderValue val)}'";

  # Render all options for a named section
  # path is e.g. "network.lan"
  renderSectionOptions =
    path: attrs:
    let
      keys = builtins.filter (k: k != "_type" && k != "_order") (lib.attrNames attrs);
    in
    lib.concatMapStringsSep "\n" (k: renderOption path k attrs.${k}) keys;

  # Render a single named section within a package
  # Returns a string of UCI commands
  renderSection =
    pkg: name: attrs:
    let
      sectionType = attrs._type or name;
      path = "${pkg}.${name}";
    in
    ''
      uci set '${path}=${sectionType}'
      ${renderSectionOptions path attrs}
    '';

  # Render an entire package (collection of named sections)
  # sections :: attrset of { sectionName = { _type; options… }; }
  renderPackage =
    pkg: sections:
    let
      names = lib.attrNames sections;
    in
    lib.concatMapStringsSep "\n\n" (name: renderSection pkg name sections.${name}) names;

in
{
  # Generate a complete UCI apply script for a set of packages.
  #
  # config :: { <package> = { <section> = { _type = "…"; <key> = <value>; }; }; }
  #
  # Returns a shell script string that:
  #   1. Sets all UCI values
  #   2. Commits all changed packages
  #   3. Prints a summary
  mkUciScript =
    config:
    let
      packages = lib.attrNames config;
      body = lib.concatMapStringsSep "\n\n" (pkg: renderPackage pkg config.${pkg}) packages;
      commits = lib.concatMapStringsSep "\n" (pkg: "uci commit ${pkg}") packages;
    in
    ''
      # ── UCI configuration (auto-generated by sinnix openwrt module) ──

      ${body}

      # Commit all changed packages
      ${commits}

      echo "✓ UCI configuration committed successfully."
    '';

  # Convenience: build a single named section attrset
  # Usage: mkSection "interface" { proto = "dhcp"; device = "wan"; }
  mkSection = type: opts: { _type = type; } // opts;

  # Build an opkg install script for a list of package names
  mkOpkgScript =
    packages:
    let
      pkgList = lib.concatStringsSep " " packages;
    in
    ''
      #!/bin/sh
      set -eu
      echo "Updating opkg package lists..."
      opkg update
      echo "Installing packages: ${pkgList}"
      opkg install ${pkgList}
      echo "✓ Packages installed."
    '';
}
