#!/usr/bin/env bash
# @sinnix-package
# description: Mount Nextcloud WebDAV share
# runtimeInputs: coreutils util-linux
set -euo pipefail
if mountpoint -q /mnt/nextcloud; then
  echo "Nextcloud is already mounted"
  exit 0
fi
sudo systemctl start mnt-nextcloud.mount
